declare const classNames: {
  readonly "theme-light": "theme-light";
  readonly "theme-dark": "theme-dark";
  readonly main: "main";
  readonly product__container: "product__container";
  readonly product__container_loading: "product__container_loading";
  readonly product: "product";
  readonly slider: "slider";
  readonly info: "info";
  readonly heading: "heading";
  readonly descr: "descr";
  readonly price: "price";
  readonly actions: "actions";
  readonly title: "title";
  readonly list: "list";
  readonly product__button: "product__button";
  readonly product__button_now: "product__button_now";
  readonly img: "img";
  readonly related: "related";
};
export = classNames;
