declare const classNames: {
  readonly cart: "cart";
  readonly heading: "heading";
  readonly amount: "amount";
  readonly block: "block";
  readonly main: "main";
  readonly list: "list";
  readonly payment: "payment";
  readonly payment__main: "payment__main";
  readonly payment__info: "payment__info";
  readonly payment__heading: "payment__heading";
  readonly payment__line: "payment__line";
  readonly payment__line_main: "payment__line_main";
  readonly payment__button: "payment__button";
  readonly modul: "modul";
  readonly title: "title";
  readonly price__discount: "price__discount";
  readonly modal__main: "modal__main";
  readonly modal__title: "modal__title";
  readonly modal__price: "modal__price";
  readonly modal__actions: "modal__actions";
  readonly modal__payment: "modal__payment";
  readonly modal__cancle: "modal__cancle";
};
export = classNames;
